### PR TITLE
build fixes and warnings

### PR DESCRIPTION
**Pull request by gim**
I've corrected the argument in AC_CONFIG_SRCDIR which prevented me from building, removed the now unnecessary configure, and removed the duplicate definitions of memmem (and configured to allow its use from the system headers).

### CODE REVIEW

**Comment by rlp1938** [comment]
Thanks for your efforts. The reason it built for me was that I had a binary backup in place. But I thought ./configure was expected to have most contingencies covered so that the end user had no need of autotools. Your thoughts please.

**Comment by gim** [comment]
On Thu, 29 Jan 2015 23:07:26 -0800
Robert L Parker notifications@github.com wrote:

> Thanks for your efforts. The reason it built for me was that I had a
> binary backup in place. But I thought ./configure was expected to
> have most contingencies covered so that the end user had no need of
> autotools. Your thoughts please.

configure is generally not committed to the repository as running 'make
dist' will generate a tarball with a copy of configure which a user
can run.

This slightly complicates building from a new checkout for developers,
but running autoreconf (or autogen.sh) takes care of this.
Unfortunately github's policy of providing the "Download ZIP" button
for the raw source conflates the two use cases somewhat.

Some people do commit configure if they can't be sure all the m4
dependencies will be present on the developers machine, or they can't
commit the dependencies for some reason. But as you don't seem to be
using AX_ or AS_ macros removing configure seems fairly straightforward.

**Comment by rlp1938** [comment]
Ok thanks. I will change to use 'make dist' and and add the tarball to the repository. Git hub can't merge your pull request so I'll have to learn to use the patch I suppose.

**Comment by gim** [comment]
On 2015-01-30 22:33, Robert L Parker wrote:

> Ok thanks. I will change to use 'make dist' and and add the tarball to
> the repository. Git hub can't merge your pull request so I'll have to
> learn to use the patch I suppose.

There's no need to add the tarball directly. Users who checkout direct 
from github should be capable of generating configure themselves, and 
people getting it indirectly from a package system shouldn't need to 
care either way.

If you _really_ need it to be instantly configurable then I'd retain the 
configure script in preference to committing a tarball, else I would add 
a quick note to a README/INSTALL which suggests developers run 'autoconf 
-i' to generate 'configure'.

**Comment by rlp1938** [comment]
I do think that I want to make this system accessible to those without git and/or autotools so I will reinstate ./configure.

**Pull request merged**
